version: '3.8'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.6'
    container_name: elasticsearch
    environment:
      - node.master=true
      - "ES_JAVA_OPTS=-Xms800m -Xmx800m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1800m
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:6.8.6'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    mem_limit: 500m
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  configure_stack:
    container_name: load-data
    build: ./load-data
    mem_limit: 200m
    command:
      - /bin/bash
      - '-c'
      - cat /tmp/data/load-data.sh | tr -d "\r" | bash
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local